# =====================================================================
# Remote State Data Sources
# =====================================================================
data "terraform_remote_state" "aws_networking" {
  backend = "s3"
  config = {
    region = var.aws_region
    bucket = var.statefile_bucket_name
    key    = "terraform/aws/networking/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_security" {
  backend = "s3"
  config = {
    region = var.aws_region
    bucket = var.statefile_bucket_name
    key    = "terraform/aws/security/terraform.tfstate"
  }
}

# =====================================================================
# Ubuntu AMI Data Source - Latest Ubuntu 24.04 LTS
# =====================================================================
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# =====================================================================
# EC2 Instance - Ubuntu SIA Target
# =====================================================================
resource "aws_instance" "ubuntu_sia_target" {
  ami                  = data.aws_ami.ubuntu.id
  instance_type        = var.instance_type
  subnet_id            = data.terraform_remote_state.aws_networking.outputs.private_subnet_id_a
  key_name             = data.terraform_remote_state.aws_security.outputs.key_pair_name
  iam_instance_profile = data.terraform_remote_state.aws_security.outputs.ec2_asm_instance_profile_name
  vpc_security_group_ids = [
    data.terraform_remote_state.aws_security.outputs.ssh_internal_flat_sg_id,
    data.terraform_remote_state.aws_security.outputs.https_internal_flat_sg_id
  ]

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 30
    delete_on_termination = true
    encrypted             = true
  }

  tags = {
    Name                 = "${lower(var.alias)}-ubuntu-sia-target-1"
    Project              = var.alias
    I_Owner              = var.asset_owner_name
    I_Purpose            = "${var.alias} Lab Linux SIA Target"
    CA_iScheduler        = var.iScheduler
    CA_iSchedulerControl = "yes"
  }

  lifecycle {
    ignore_changes = [tags, ami]
  }
}
/*
resource "terraform_data" "wait_for_ssh_ubuntu_sia" {
  provisioner "remote-exec" {
    connection {
      host        = aws_instance.ubuntu_sia_target.private_ip
      user        = var.ubuntu_username
      private_key = file("${path.module}/../../.ssh/default_ssh_key.pem")
    }

    inline = [
      "echo 'Waiting for user data script to finish'",
      "cloud-init status --wait > /dev/null"
    ]
  }
}

# =====================================================================
# CyberArk SIA Target Configuration
# =====================================================================
resource "idsec_sia_ssh_public_key" "ubuntu_sia_target_configure" {
  target_machine   = aws_instance.ubuntu_sia_target.private_ip
  username         = var.ubuntu_username
  private_key_path = "${path.module}/../../.ssh/default_ssh_key.pem"

  depends_on = [
    aws_instance.ubuntu_sia_target,
  ]
}

# =====================================================================
# Create Access Policy for SIA Target
# =====================================================================
data "idsec_identity_role" "linux_admins_role" {
  role_name = "${var.alias} Linux Admins"
}

resource "idsec_policy_vm" "ubuntu_sia_target_policy" {
  metadata = {
    name        = "${var.alias} Ubuntu SIA Target",
    description = "Autogenerated policy for Ubuntu SIA Target in ${var.alias} project",
    status = {
      status = "Active"
    },
    policy_entitlement = {
      target_category = "VM",
      location_type   = "AWS"
    },
    policy_tags = [],
    time_zone   = "America/New_York"
  }
  principals = [
    {
      id   = data.idsec_identity_role.linux_admins_role.role_id,
      name = data.idsec_identity_role.linux_admins_role.role_name,
      type = "ROLE"
    }
  ]
  conditions = {
    access_window = {
      days_of_the_week = [1, 2, 3, 4, 5, 6],
      from_hour        = "09:00",
      to_hour          = "17:00"
    },
    max_session_duration = 8
  }
  targets = {
    awsResource = {
      region  = var.aws_region,
      vpc_ids = [data.terraform_remote_state.aws_foundation.outputs.vpc_id],
      tags = [
        {
          "Project" = var.alias
        }
      ]
    }
  }
  behavior = {
    sshProfile = {
      username = var.ubuntu_username
    }
  }
}
*/